### ISSUE TITLE
Feature: Any plan to support Embeddings?

### ISSUE THREAD

**Issue by nowa** [LevitatingBusinessMan/openai-rust#1]
Embeddings also is a common api to build services, any plan for that? Thanks, :)

**Comment by LevitatingBusinessMan** [comment]
Hey, thanks for taking interest in the project. I am sorry your issue kind of went under my radar. I plan to add more endpoints soon, so I might add Embeddings. However feel free to make contributions.

**Comment by LevitatingBusinessMan** [comment]
Added in https://github.com/LevitatingBusinessMan/openai-rust/commit/50fc6a04de667b7c8954472fe1e84ee4d9ad3f8a
